// Проверки на ошибки, а не на стиль: необъявленные переменные, недостижимый код, опечатки в сравнениях.
// Запуск: npx eslint . (в CI — отдельный шаг, в проекте нет npm-зависимостей).
const browser = { window:1, document:1, location:1, history:1, navigator:1, fetch:1, EventSource:1, URL:1, URLSearchParams:1, localStorage:1, sessionStorage:1, setTimeout:1, clearTimeout:1, setInterval:1, clearInterval:1, requestAnimationFrame:1, cancelAnimationFrame:1, console:1, innerWidth:1, innerHeight:1, scrollX:1, scrollY:1, matchMedia:1, Intl:1, crypto:1, TextEncoder:1, TextDecoder:1, alert:1, confirm:1, prompt:1, AudioContext:1, getComputedStyle:1, HTMLElement:1, Event:1, CustomEvent:1, BarcodeDetector:1, addEventListener:1, removeEventListener:1, queueMicrotask:1, performance:1, structuredClone:1, screen:1, visualViewport:1, ResizeObserver:1, IntersectionObserver:1, MutationObserver:1, atob:1, btoa:1, Blob:1, File:1, FormData:1, Image:1, AbortController:1, DOMException:1, globalThis:1, self:1, print:1 };
const node = { process:1, Buffer:1, console:1, setTimeout:1, clearTimeout:1, setInterval:1, clearInterval:1, URL:1, URLSearchParams:1, globalThis:1, structuredClone:1, AbortController:1, TextEncoder:1, fetch:1, queueMicrotask:1, performance:1 };
const g = (o) => Object.fromEntries(Object.keys(o).map((k) => [k, 'readonly']));
const rules = { 'no-undef': 'error', 'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }], 'no-unreachable': 'error', 'no-dupe-keys': 'error', 'no-self-assign': 'error', 'no-constant-condition': ['warn', { checkLoops: false }], 'no-cond-assign': ['error', 'except-parens'], 'eqeqeq': ['warn', 'smart'], 'no-shadow-restricted-names': 'error', 'no-redeclare': 'error', 'no-unsafe-finally': 'error', 'no-unsafe-negation': 'error', 'use-isnan': 'error', 'valid-typeof': 'error', 'no-fallthrough': 'error', 'no-empty': ['warn', { allowEmptyCatch: true }], 'no-use-before-define': ['error', { functions: false, classes: false, variables: false }], 'no-loss-of-precision': 'error', 'no-dupe-else-if': 'error', 'no-duplicate-imports': 'error', 'no-async-promise-executor': 'error', 'require-atomic-updates': 'off', 'no-await-in-loop': 'off', 'no-promise-executor-return': 'error', 'no-template-curly-in-string': 'warn', 'array-callback-return': 'error', 'no-unmodified-loop-condition': 'error' };
export default [
  { files: ['public/**/*.js', 'tools/claude-demo/src/**/*.js'], languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: g(browser) }, rules },
  { files: ['server/**/*.js', 'test/**/*.js', 'scripts/**/*.mjs', 'eslint.config.mjs'], languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: g(node) }, rules },
  // код внутри page.evaluate() выполняется в браузере
  { files: ['test/e2e/**/*.js'], languageOptions: { globals: { ...g(node), ...g(browser) } } },
  { ignores: ['public/vendor/**', 'tools/claude-demo/build/**', '.claude/**', 'node_modules/**'] },
];
